name: Transfer Vercel secrets

on:
  workflow_dispatch:

jobs:
  transfer:
    runs-on: ubuntu-latest

    steps:
      - name: secrets to external repo
        env:
          GH_TOKEN: ${{ secrets.DESTINATION_GITHUB_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          printf '%s' "$VERCEL_ORG_ID" | gh secret set VERCEL_ORG_ID --repo dasbap/fleet-test
          printf '%s' "$VERCEL_PROJECT_ID" | gh secret set VERCEL_PROJECT_ID --repo dasbap/fleet-test
          printf '%s' "$VERCEL_TOKEN" | gh secret set VERCEL_TOKEN --repo dasbap/fleet-test
